server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: identity-test
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/identity/api/test
          filters:
            - StripPrefix=1
        - id: employee-test
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employee/api/test
          filters:
            - StripPrefix=1
        - id: employee-service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employee/api/employees/**
          filters:
            - StripPrefix=1
        - id: department-test
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/department/api/test
          filters:
            - StripPrefix=1
        - id: department-service
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/department/api/departments/**
          filters:
            - StripPrefix=1
        - id: customer-test
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/api/test
          filters:
            - StripPrefix=1
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/api/customers/**
          filters:
            - StripPrefix=1
        - id: hr-test
          uri: lb://HR-SERVICE
          predicates:
            - Path=/hr/api/test
          filters:
            - StripPrefix=1
        - id: hr-service
          uri: lb://HR-SERVICE
          predicates:
            - Path=/hr/api/hr-records/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
