Manifest-Version=1.0
Implementation-Title=com.netflix.eureka#eureka-client-jersey3;2.0.2
Implementation-Version=2.0.2
Built-Status=integration
Built-By=runner
Built-OS=Linux
Build-Timezone=Etc/UTC
Build-Date-UTC=2024-02-13T23:57:27.148670Z
Build-Date=2024-02-13_23:57:27
Gradle-Version=7.5.1
Module-Source=/eureka-client-jersey3
Module-Origin=https://github.com/Netflix/eureka
Change=3a63288
Full-Change=3a63288b9433242b6b558fbd79d87d39ffc86f4d
Branch=3a63288b9433242b6b558fbd79d87d39ffc86f4d
Build-Host=https://github.com
Build-Job=__run_2
Build-Number=16
Build-Id=7894316699
Build-Url=https://github.com/Netflix/eureka/actions/runs/7894316699
Created-By=11.0.22+7-LTS (Azul Systems, Inc.)
Module-Owner=netflixoss@netflix.com
Module-Email=netflixoss@netflix.com
X-Compile-Target-JDK=1.8
X-Compile-Source-JDK=1.8
Build-Java-Version=11.0.22